# Generated by Django 4.2.7 on 2023-11-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=8)),
                ('job_number', models.PositiveIntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(max_length=70, unique=True)),
                ('department', models.CharField(default='', max_length=20)),
                ('permission', models.CharField(choices=[('doc', 'Doctor'), ('sec', 'Secretary'), ('doc&head', 'Doctor and Head')], default='doc', max_length=15)),
                ('no_stu_in_internship', models.PositiveSmallIntegerField(default=0)),
                ('no_stu_in_grasduation_project', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
