# Generated by Django 5.0 on 2023-12-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doctor_email_remove_doctor_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
