# Generated by Django 5.0 on 2023-12-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='type',
        ),
    ]
