# Generated by Django 5.0 on 2023-12-31 16:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_doctor_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doctor_notification',
            new_name='DoctorNotification',
        ),
    ]
