# Generated by Django 5.0 on 2023-12-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_doctornotification_query_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotification',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
