# Generated by Django 5.0 on 2023-12-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0011_alter_doctornotification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
