# Generated by Django 5.0 on 2023-12-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_dept_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Computer Information Systems', 'Computer Information Systems'), ('Business Information Technology', 'Business Information Technology'), ('Data Science', 'Data Science'), ('Cyber Security', 'Cyber Security'), ('Artificial Intelligence', 'Artificial Intelligence')], max_length=32),
        ),
    ]
