# Generated by Django 5.0 on 2023-12-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='no_of_stu_exceed_90',
        ),
        migrations.RemoveField(
            model_name='department',
            name='no_of_stud_in_dept',
        ),
        migrations.AddField(
            model_name='department',
            name='num_team_member',
            field=models.PositiveSmallIntegerField(default=4, verbose_name="Number of team's member"),
        ),
    ]
