# Generated by Django 5.0 on 2023-12-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_rename_department_notification_departmentnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentnotification',
            name='query_pk',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='departmentnotification',
            name='url_name',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
