# Generated by Django 5.0 on 2023-12-31 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_departmentnotification_query_pk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentnotification',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
