# Generated by Django 5.0 on 2024-01-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_alter_departmentnotification_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='week',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
