# Generated by Django 5.0 on 2024-01-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_department_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='week',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
