# Generated by Django 4.2.7 on 2023-11-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=9)),
                ('student_id', models.CharField(default='', max_length=6)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=70)),
                ('gender', models.CharField(default='', max_length=6)),
                ('major', models.CharField(default='', max_length=20)),
                ('hours', models.PositiveSmallIntegerField(default=0)),
                ('in_internship', models.BooleanField(default=False)),
                ('in_gp', models.BooleanField(default=False, verbose_name='in graduation-project')),
            ],
        ),
    ]
