# Generated by Django 5.0 on 2023-12-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=80, verbose_name='Company Name')),
                ('address', models.CharField(max_length=80)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('name', models.CharField(max_length=80, verbose_name='Superviser Name')),
                ('email', models.EmailField(max_length=80)),
                ('description_of_tasks', models.CharField(max_length=450)),
                ('technologies', models.CharField(max_length=450)),
            ],
        ),
    ]
