# Generated by Django 5.0 on 2023-12-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_stu_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
