# Generated by Django 5.0 on 2023-12-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_student_email_remove_student_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
