# Generated by Django 5.0 on 2023-12-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_remove_companyinternship_stu_companyinternship_st'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinternship',
            old_name='st',
            new_name='student',
        ),
    ]
