# Generated by Django 5.0 on 2023-12-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_rename_st_companyinternship_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
