# Generated by Django 5.0 on 2023-12-15 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_student_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='type',
            field=models.CharField(default='Student', max_length=10),
        ),
        migrations.CreateModel(
            name='WeeklyFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=64)),
                ('task', models.CharField(max_length=50)),
                ('hours', models.PositiveSmallIntegerField()),
                ('technologies', models.TextField(max_length=450)),
                ('evaluation', models.CharField(max_length=16)),
                ('stu_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
