# Generated by Django 5.0 on 2023-12-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_alter_student_type_weeklyfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.CharField(default='', max_length=32),
        ),
    ]
