# Generated by Django 5.0 on 2023-12-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_alter_student_major'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='type',
        ),
    ]
