# Generated by Django 5.0 on 2023-12-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_student_internship_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyfollowing',
            old_name='hours',
            new_name='hour',
        ),
        migrations.RemoveField(
            model_name='weeklyfollowing',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='weeklyfollowing',
            name='stu_name',
        ),
        migrations.RemoveField(
            model_name='weeklyfollowing',
            name='stu_user',
        ),
        migrations.RemoveField(
            model_name='weeklyfollowing',
            name='technologies',
        ),
        migrations.AddField(
            model_name='weeklyfollowing',
            name='sw_hw',
            field=models.TextField(max_length=650, null=True),
        ),
    ]
