# Generated by Django 5.0 on 2023-12-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_weeklyfollowing_stu_user_weeklyfollowing_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='internship_type',
        ),
        migrations.AddField(
            model_name='student',
            name='doc_superviser',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
