# Generated by Django 5.0 on 2023-12-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_remove_student_internship_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='int_acc',
            field=models.BooleanField(default=False, verbose_name='internship acceptance'),
        ),
    ]
