# Generated by Django 5.0 on 2023-12-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_student_int_acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='int_acc',
        ),
        migrations.AddField(
            model_name='companyinternship',
            name='int_com_acc',
            field=models.BooleanField(default=False, verbose_name='internship acceptance'),
        ),
        migrations.AddField(
            model_name='courseinternship',
            name='int_cor_acc',
            field=models.BooleanField(default=False, verbose_name='internship acceptance'),
        ),
    ]
