# Generated by Django 5.0 on 2023-12-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0029_remove_student_int_acc_companyinternship_int_com_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinternship',
            name='doc_note',
            field=models.CharField(max_length=450, null=True),
        ),
    ]
