# Generated by Django 5.0 on 2023-12-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_companyinternship_doc_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinternship',
            name='doc_note',
            field=models.TextField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='companyinternship',
            name='doc_note',
            field=models.TextField(max_length=450, null=True),
        ),
    ]
