# Generated by Django 5.0 on 2023-12-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_alter_companyinternship_doc_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinternship',
            name='doc_note',
        ),
        migrations.RemoveField(
            model_name='courseinternship',
            name='doc_note',
        ),
    ]
