# Generated by Django 5.0 on 2023-12-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_remove_student_doc_superviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='doc_superviser',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
