# Generated by Django 5.0 on 2023-12-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_alter_courseinternship_certificate_graduationproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationproject',
            name='major',
        ),
        migrations.RemoveField(
            model_name='graduationproject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='graduationproject',
            name='stu_id',
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='students_info',
            field=models.FileField(null=True, upload_to='Files/Graduation-Project/%Y/%B/'),
        ),
        migrations.AlterField(
            model_name='graduationproject',
            name='project_goal',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='graduationproject',
            name='project_idea',
            field=models.TextField(max_length=720),
        ),
        migrations.AlterField(
            model_name='graduationproject',
            name='technologies',
            field=models.TextField(max_length=400),
        ),
    ]
