# Generated by Django 5.0 on 2023-12-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_remove_graduationproject_stu_gp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationproject',
            name='project_type',
            field=models.CharField(choices=[('Application', 'Application'), ('Research', 'Research')], max_length=12),
        ),
    ]
