# Generated by Django 5.0 on 2023-12-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_alter_graduationproject_project_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationproject',
            name='students_info',
        ),
    ]
