# Generated by Django 5.0 on 2023-12-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0045_remove_graduationproject_students_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduationproject',
            old_name='stu_gp',
            new_name='members',
        ),
    ]
