# Generated by Django 5.0 on 2023-12-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_rename_stu_gp_graduationproject_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.BooleanField(default=False)),
                ('update', models.BooleanField(default=False)),
                ('final_release', models.BooleanField(default=False)),
                ('new_release', models.BooleanField(default=False)),
                ('research', models.BooleanField(default=False)),
                ('programming', models.BooleanField(default=False)),
                ('problem', models.BooleanField(default=False)),
                ('web', models.BooleanField(default=False)),
                ('mobile', models.BooleanField(default=False)),
                ('network', models.BooleanField(default=False)),
                ('cyber_security', models.BooleanField(default=False)),
                ('ai', models.BooleanField(default=False)),
                ('machine_learning', models.BooleanField(default=False)),
                ('post', models.TextField()),
            ],
        ),
    ]
