# Generated by Django 5.0 on 2023-12-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0049_timeline_date_timeline_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationproject',
            name='superviser',
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='email_1',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='email_2',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='superviser_1',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='graduationproject',
            name='superviser_2',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
