# Generated by Django 5.0 on 2023-12-29 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0051_timeline_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='student.graduationproject'),
        ),
    ]
