# Generated by Django 5.0 on 2023-12-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0054_rename_student_notification_studentnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentnotification',
            old_name='studentt',
            new_name='student',
        ),
    ]
