# Generated by Django 5.0 on 2024-01-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0055_rename_studentt_studentnotification_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
