# Generated by Django 5.0 on 2024-01-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0056_timeline_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotification',
            name='query_pk',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='url_name',
            field=models.CharField(max_length=24, null=True),
        ),
    ]
