# Generated by Django 5.0 on 2024-01-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0058_alter_graduationproject_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='courseinternship',
            name='doc_note',
            field=models.TextField(default='There is no any note yet.', max_length=450, null=True),
        ),
    ]
