# Generated by Django 5.0 on 2024-01-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0059_timeline_files_alter_courseinternship_doc_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimlineFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='Files/GP/Timeline/%Y/%B/%A')),
            ],
        ),
        migrations.AlterField(
            model_name='courseinternship',
            name='certificate',
            field=models.FileField(null=True, upload_to='Internship/Courses/%Y/%B'),
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='files',
        ),
        migrations.AddField(
            model_name='timeline',
            name='files',
            field=models.ManyToManyField(to='student.timlinefiles'),
        ),
    ]
