# Generated by Django 5.0 on 2024-01-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0060_timlinefiles_alter_courseinternship_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timlinefiles',
            name='file',
            field=models.FileField(null=True, upload_to='GP/Timeline/%Y/%B/%A'),
        ),
    ]
