# Generated by Django 5.0 on 2024-01-12 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0061_alter_timlinefiles_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('web_dev', models.FloatField(default=0.0)),
                ('network', models.FloatField(default=0.0)),
                ('security', models.FloatField(default=0.0)),
                ('data_science', models.FloatField(default=0.0)),
                ('description', models.TextField(default='')),
                ('weekly_hours', models.IntegerField(default=0.0)),
                ('title_sub', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='companyinternship',
            name='doc_note',
            field=models.TextField(default='There is no Notes', max_length=450, null=True),
        ),
        migrations.CreateModel(
            name='GraduationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('technologies_used', models.CharField(max_length=255)),
                ('what_to_learn', models.TextField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.recommendedproject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_dev_rating', models.FloatField()),
                ('network_rating', models.FloatField()),
                ('security_rating', models.FloatField()),
                ('data_science_rating', models.FloatField()),
                ('stu_username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
