# Generated by Django 5.0 on 2024-01-12 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0062_recommendedproject_alter_companyinternship_doc_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrating',
            name='stu_username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
