# Generated by Django 5.0 on 2024-01-12 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0065_remove_recommendedproject_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationdetails',
            name='project',
        ),
        migrations.AddField(
            model_name='recommendedproject',
            name='details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.graduationdetails'),
        ),
    ]
